name: kid_manager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # i18n / localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  dropdown_button2: ^2.3.9

  # Firebase (đồng bộ major)
  firebase_core: ^4.2.1
  firebase_app_check: ^0.4.1+1
  firebase_auth: ^6.1.2
  firebase_database: ^12.1.0
  firebase_storage: ^13.0.4
  path: ^1.9.0
  cloud_firestore: 6.1.0
  firebase_messaging: ^16.0.4

  # Map
  latlong2: ^0.9.1
  polyline_codec: ^0.1.6

  # E2EE / Security
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.3

  image: ^4.1.3
  crop_your_image: ^1.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # Location background
  location: ^8.0.1
  geolocator: ^14.0.2

  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  android_intent_plus: ^5.1.2
  installed_apps: ^2.1.1
  path_provider: ^2.1.4
  usage_stats: ^1.2.0

  # Local / Network / Utils
  http: ^1.2.0
  logger: ^2.0.1

  # Activity / Env / Mapbox
  flutter_activity_recognition: ^4.0.0
  flutter_dotenv: ^5.1.0
  mapbox_maps_flutter: ^2.18.0

  workmanager: ^0.6.0

  # SOS
  cloud_functions: ^6.0.0
  flutter_local_notifications: ^17.0.0
  just_audio: ^0.9.38
  uuid: ^4.4.0
  app_settings: ^5.1.1
  video_player: ^2.11.0

  # Export Excel
  file_picker: ^8.0.0
  excel: ^4.0.2
  share_plus: ^10.0.2
  open_filex: ^4.7.0
  file_saver: ^0.2.13
  flutter_file_dialog: ^3.0.3
  #  Phone
  flutter_native_contact_picker: ^0.0.10
  url_launcher: ^6.3.0

  # Auth socials
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  battery_plus: 7.0.0
  skeletonizer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_app_kid.png"
  adaptive_icon_foreground: "assets/icons/icon_app_kid.png"
  adaptive_icon_background: "#00000000"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/stickers/family_chat/celebrate.webp
    - assets/videos/
    - assets/sounds/sos.mp3
    - assets/templates/schedule_template.xlsx
    - assets/zones/i18n/
    - assets/map/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
