// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4VAU2dStmg1zzk62WSTGmXb4BBoczFM',
    appId: '1:1081020222417:web:28d92322d064c732c46ef0',
    messagingSenderId: '1081020222417',
    projectId: 'kidmanager-b4a8f',
    authDomain: 'kidmanager-b4a8f.firebaseapp.com',
    storageBucket: 'kidmanager-b4a8f.firebasestorage.app',
    measurementId: 'G-5Y4K800WJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbScXNJezV8Vj4_edhig2_o05yuI1Fnc0',
    appId: '1:1081020222417:android:ba0f8a2945751480c46ef0',
    messagingSenderId: '1081020222417',
    projectId: 'kidmanager-b4a8f',
    storageBucket: 'kidmanager-b4a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWS_kgD7Uk0d8hzeBeFuY-7UM-fWbMVg',
    appId: '1:1081020222417:ios:0ad813dad802d111c46ef0',
    messagingSenderId: '1081020222417',
    projectId: 'kidmanager-b4a8f',
    storageBucket: 'kidmanager-b4a8f.firebasestorage.app',
    iosBundleId: 'com.example.kidManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWS_kgD7Uk0d8hzeBeFuY-7UM-fWbMVg',
    appId: '1:1081020222417:ios:0ad813dad802d111c46ef0',
    messagingSenderId: '1081020222417',
    projectId: 'kidmanager-b4a8f',
    storageBucket: 'kidmanager-b4a8f.firebasestorage.app',
    iosBundleId: 'com.example.kidManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4VAU2dStmg1zzk62WSTGmXb4BBoczFM',
    appId: '1:1081020222417:web:6305dbcabc314d74c46ef0',
    messagingSenderId: '1081020222417',
    projectId: 'kidmanager-b4a8f',
    authDomain: 'kidmanager-b4a8f.firebaseapp.com',
    storageBucket: 'kidmanager-b4a8f.firebasestorage.app',
    measurementId: 'G-3L3R7YY8DB',
  );
}
